name: build

on:
  workflow_dispatch:
jobs:
  build:
    if: ${{always()}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2019,windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
        with:
          submodules: recursive
      - name: run bat file
        shell: cmd
        run: |
          call ./cmd.bat
      - name: run bat file
        run: |
            ./cmd.bat
