name: build

on:
  workflow_dispatch:
jobs:
  build:
    if: ${{always()}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2019,windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - name: crlf
        shell: cmd
        run: |
          git config --system core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v3 
        with:
          submodules: recursive
      - name: run bat file
        shell: cmd
        run: |
          call ./cmd.bat
      - name: run bat file
        run: |
            ./cmd.bat
      - uses: msys2/setup-msys2@v2
        id: msys2
        with:
          location: ./
      - env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
        run: echo "$env:MSYS2_LOCATION"
